---
# See https://docs.ansible.com/projects/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ceru1ean
name: homelab
version: 0.1.0
readme: README.md
authors:
  - Leonardo Buoncompagni <0x07cf@pm.me>
description: This collection provides a set of roles for my homelab.
license_file: LICENSE
tags:
  - linux
  - homelab
repository: https://github.com/0x07cf-dev/ansible-collection-homelab
# documentation: https://github.com/0x07cf-dev/ansible-collection-homelab/tree/main/docs
homepage: https://github.com/0x07cf-dev/ansible-collection-homelab
issues: https://github.com/0x07cf-dev/ansible-collection-homelab/issues
build_ignore:
  # https://docs.ansible.com/projects/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
